import Head from "next/head";
import Image from "next/image";
import RiveComponentFlutter from "@components/rive-component";
import RiveComponentSearch from "@components/rive-search";
import styles from "@styles/Home.module.css";

export default function Home() {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                {/* ====== Navbar Section Start */}

                <div
                    className="
  ud-header
  bg-transparent
  z-40
  w-full
  flex
  items-center
  bg-blue-500
"
                >
                    <div className="container">
                        <div className="flex mx-4 items-center justify-between relative">
                            <div className="px-4 w-60 max-w-full">
                                <a
                                    href="index.html"
                                    className="navbar-logo w-full block py-5"
                                >
                                    <img
                                        src="/vercel.svg"
                                        alt="logo"
                                        className="w-full header-logo"
                                    />
                                </a>
                            </div>
                            <div className="flex px-4 justify-between items-center w-full">
                                <div>
                                    <button
                                        id="navbarToggler"
                                        className="
            block
            absolute
            right-4
            top-1/2
            -translate-y-1/2
            lg:hidden
            focus:ring-2
            ring-primary
            px-3
            py-[6px]
            rounded-lg
          "
                                    >
                                        <span className="relative w-[30px] h-[2px] my-[6px] block bg-white" />
                                        <span className="relative w-[30px] h-[2px] my-[6px] block bg-white" />
                                        <span className="relative w-[30px] h-[2px] my-[6px] block bg-white" />
                                    </button>
                                    <nav
                                        id="navbarCollapse"
                                        className="
            absolute
            py-5
            lg:py-0 lg:px-4
            xl:px-6
            bg-white
            lg:bg-transparent
            shadow-lg
            rounded-lg
            max-w-[250px]
            w-full
            lg:max-w-full lg:w-full
            right-4
            top-full
            hidden
            lg:block lg:static lg:shadow-none
          "
                                    >
                                        <ul className="blcok lg:flex">
                                            <li className="relative group">
                                                <a
                                                    href="#home"
                                                    className="
                  ud-menu-scroll
                  text-base text-dark
                  lg:text-white
                  lg:group-hover:opacity-70
                  lg:group-hover:text-white
                  group-hover:text-primary
                  py-2
                  lg:py-6 lg:inline-flex lg:px-0
                  flex
                  mx-8
                  lg:mr-0
                "
                                                >
                                                    Home
                                                </a>
                                            </li>
                                            <li className="relative group">
                                                <a
                                                    href="#about"
                                                    className="
                  ud-menu-scroll
                  text-base text-dark
                  lg:text-white
                  lg:group-hover:opacity-70
                  lg:group-hover:text-white
                  group-hover:text-primary
                  py-2
                  lg:py-6 lg:inline-flex lg:px-0
                  flex
                  mx-8
                  lg:mr-0 lg:ml-7
                  xl:ml-12
                "
                                                >
                                                    About
                                                </a>
                                            </li>
                                            <li className="relative group">
                                                <a
                                                    href="#showcase"
                                                    className="
                  ud-menu-scroll
                  text-base text-dark
                  lg:text-white
                  lg:group-hover:opacity-70
                  lg:group-hover:text-white
                  group-hover:text-primary
                  py-2
                  lg:py-6 lg:inline-flex lg:px-0
                  flex
                  mx-8
                  lg:mr-0 lg:ml-7
                  xl:ml-12
                "
                                                >
                                                    Projects Showcase
                                                </a>
                                            </li>
                                            <li className="relative group">
                                                <a
                                                    href="#team"
                                                    className="
                  ud-menu-scroll
                  text-base text-dark
                  lg:text-white
                  lg:group-hover:opacity-70
                  lg:group-hover:text-white
                  group-hover:text-primary
                  py-2
                  lg:py-6 lg:inline-flex lg:px-0
                  flex
                  mx-8
                  lg:mr-0 lg:ml-7
                  xl:ml-12
                "
                                                >
                                                    Team
                                                </a>
                                            </li>
                                            <li className="relative group">
                                                <a
                                                    href="#contact"
                                                    className="
                  ud-menu-scroll
                  text-base text-dark
                  lg:text-white
                  lg:group-hover:opacity-70
                  lg:group-hover:text-white
                  group-hover:text-primary
                  py-2
                  lg:py-6 lg:inline-flex lg:px-0
                  flex
                  mx-8
                  lg:mr-0 lg:ml-7
                  xl:ml-12
                "
                                                >
                                                    Contact
                                                </a>
                                            </li>
                                            <li className="relative group submenu-item">
                                                <a
                                                    href="javascript:void(0)"
                                                    className="
                  text-base text-dark
                  lg:text-white
                  lg:group-hover:opacity-70
                  lg:group-hover:text-white
                  group-hover:text-primary
                  py-2
                  lg:py-6 lg:inline-flex lg:pl-0 lg:pr-4
                  flex
                  mx-8
                  lg:mr-0 lg:ml-8
                  xl:ml-12
                  relative
                  after:absolute
                  after:w-2
                  after:h-2
                  after:border-b-2
                  after:border-r-2
                  after:border-current
                  after:rotate-45
                  lg:after:right-0
                  after:right-1
                  after:top-1/2
                  after:-translate-y-1/2
                  after:mt-[-2px]
                "
                                                >
                                                    Projects
                                                </a>
                                                <div
                                                    className="
                  submenu
                  hidden
                  relative
                  lg:absolute
                  w-[250px]
                  top-full
                  lg:top-[110%]
                  left-0
                  rounded-sm
                  lg:shadow-lg
                  p-4
                  lg:block lg:opacity-0 lg:invisible
                  group-hover:opacity-100
                  lg:group-hover:visible lg:group-hover:top-full
                  bg-white
                  transition-[top]
                  duration-300
                "
                                                >
                                                    <a
                                                        href="https://github.com/WebDux-Tech/apk/raw/master/codee/app-release.apk"
                                                        className="
                    block
                    text-sm text-body-color
                    rounded
                    hover:text-primary
                    py-[10px]
                    px-4
                  "
                                                    >
                                                        CodeeApp
                                                    </a>
                                                    <a
                                                        href="https://play.google.com/store/apps/details?id=com.unique.kareman"
                                                        className="
                    block
                    text-sm text-body-color
                    rounded
                    hover:text-primary
                    py-[10px]
                    px-4
                  "
                                                    >
                                                        Kareman
                                                    </a>
                                                    <a
                                                        href="https://play.google.com/store/apps/details?id=com.app.mypetslife"
                                                        className="
                    block
                    text-sm text-body-color
                    rounded
                    hover:text-primary
                    py-[10px]
                    px-4
                  "
                                                    >
                                                        My Pets Life
                                                    </a>
                                                    <a
                                                        href="https://xd.adobe.com/view/5556afa8-1b1c-42ac-a2f4-f8b8724249e5-0005/"
                                                        className="
                    block
                    text-sm text-body-color
                    rounded
                    hover:text-primary
                    py-[10px]
                    px-4
                  "
                                                    >
                                                        Priority Pay
                                                    </a>
                                                    <a
                                                        href="https://play.google.com/store/apps/details?id=com.novioapp.users"
                                                        className="
                    block
                    text-sm text-body-color
                    rounded
                    hover:text-primary
                    py-[10px]
                    px-4
                  "
                                                    >
                                                        NovioApp
                                                    </a>
                                                    <a
                                                        href="https://play.google.com/store/apps/details?id=com.ripromain.users"
                                                        className="
                    block
                    text-sm text-body-color
                    rounded
                    hover:text-primary
                    py-[10px]
                    px-4
                  "
                                                    >
                                                        Ripro Constructions
                                                    </a>
                                                    <a
                                                        href="https://fast-nft.netlify.app/"
                                                        className="
                    block
                    text-sm text-body-color
                    rounded
                    hover:text-primary
                    py-[10px]
                    px-4
                  "
                                                    >
                                                        NFT Marketplace
                                                    </a>
                                                    <a
                                                        href="https://streetverse.world/"
                                                        className="
                    block
                    text-sm text-body-color
                    rounded
                    hover:text-primary
                    py-[10px]
                    px-4
                  "
                                                    >
                                                        Metaverse
                                                    </a>
                                                </div>
                                            </li>
                                        </ul>
                                    </nav>
                                </div>
                                {/*  */}
                                <div className="sm:flex justify-end hidden pr-16 lg:pr-0">
                                    <a
                                        href="tel:8668651325"
                                        className="
            text-base
            font-medium
            text-white
            hover:opacity-70
            py-3
            px-7
            loginBtn
          "
                                    >
                                        Call
                                    </a>
                                    <a
                                        href="mailto:javaoncloud14@gmail.com"
                                        className="
            text-base
            font-medium
            text-white
            bg-white bg-opacity-20
            rounded-lg
            py-3
            px-6
            hover:bg-opacity-100 hover:text-dark
            signUpBtn
            duration-300
            ease-in-out
          "
                                    >
                                        Email
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                {/* ====== Navbar Section End */}

                <div className="md:h-screen ">
                    <div className="flex flex-col md:flex-row ">
                        {/* appbar here */}
                        <div className="w-full md:w-1/2">
                            <div className=" pt-24 md:py-24 font-bold text-5xl text-center text-blue-600">
                                Build apps for any screen
                            </div>
                            <div className="flex justify-center items-center">
                                <div className="">
                                    <input type={"text"} />
                                </div>
                                <div className=" h-6 w-6 md:h-40 md:w-40">
                                    <RiveComponentSearch />
                                </div>
                            </div>
                        </div>
                        <div className="w-full  p-8 md:w-1/2">
                            <RiveComponentFlutter
                                mouseEnterEvents={console.log("playing")}
                            />
                        </div>
                    </div>
                </div>

            </main>

            <footer className={styles.footer}>
                <a
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Powered by{" "}
                    <span className={styles.logo}>
                        <Image
                            src="/vercel.svg"
                            alt="Vercel Logo"
                            width={72}
                            height={16}
                        />
                    </span>
                </a>
            </footer>
        </div>
    );
}
